/**
 * Namespace imports — `import vfs from "vfs"` as sugar over the injected global.
 *
 * Both mount paths install one field-access proxy per allow-listed service
 * namespace on the widget's `window` (see mount/bridge.ts). Globals work, but
 * they are invisible to an editor: no completion, no signatures, and no static
 * signal that a widget touches `vfs` at all. The app SDK contract
 * (registry/docs/apps-and-workflows.md, "The app SDK — what a widget imports")
 * makes the namespaces *importable* instead, which is what
 * `generateNamespaceTypes` can then describe in a `.d.ts`.
 *
 * Two rules keep this honest:
 *
 * 1. **Sugar, not a second channel.** The generated virtual module reads the
 *    global the mount already installed rather than building a second proxy,
 *    so `import vfs from "vfs"` and the `vfs` global are literally the same
 *    object. A widget can mix the two in one file and they cannot drift —
 *    same transport, same auth, same trace.
 * 2. **Only injected namespaces are intercepted.** `vfs` and `events` are also
 *    real npm packages; a widget whose manifest does not list the service must
 *    still get the package from the CDN. That is also why this plugin has to
 *    run *before* `cdnTransformPlugin`, which turns every remaining bare
 *    specifier into an esm.sh URL — esbuild consults `onResolve` callbacks in
 *    plugin order, so first registered wins.
 *
 * Deep imports (`import repos from "github/repos"`) are deliberately not
 * intercepted: the namespace root is the whole contract, and leaving subpaths
 * alone keeps a same-named real package's deep imports working.
 */

import { extractNamespaces } from "../namespace-core.js";
import type { Plugin } from "esbuild-wasm";

/** esbuild namespace the generated virtual modules live in. */
export const NAMESPACE_MODULE_NAMESPACE = "patchwork-namespace";

/**
 * The first-party namespaces that are auto-partitioned per (app, app-user).
 * Defined in `namespace-core.ts`, re-exported here for the callers that have
 * always imported it from this module.
 */
export { NATIVE_APP_NAMESPACES } from "../namespace-core.js";

/** A namespace is only importable under a name that is a valid JS identifier. */
const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export interface NamespaceImportOptions {
  /**
   * The widget manifest's `services` entries (e.g. `["vfs", "github.repos"]`).
   * Reduced to namespace roots with the same `extractNamespaces` the mount uses
   * to decide which globals to install, so imports and globals never disagree.
   */
  services?: string[];
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Source of the virtual module a namespace specifier resolves to.
 *
 * The module binds the already-installed global so the import *is* the mount's
 * proxy. When the global is not there yet (a host that evaluates widget code
 * before mounting), it falls back to a forwarder that re-reads `globalThis` on
 * every call — a late call still works, and a call that never had a namespace
 * fails with a message naming it instead of `undefined is not a function`.
 */
export function generateNamespaceModule(namespace: string): string {
  const name = JSON.stringify(namespace);
  const namedExport = IDENTIFIER.test(namespace)
    ? `\nexport { ns as ${namespace} };`
    : "";

  return `// Generated by @aprovan/patchwork-compiler for the ${name} service namespace.
const NAMESPACE = ${name};

function forward(path) {
  const call = function () {
    const target = globalThis[NAMESPACE];
    if (!target) {
      throw new Error(
        'Service namespace "' + NAMESPACE + '" is not available in this runtime'
      );
    }
    if (!path) {
      throw new Error(
        'Call a procedure on "' + NAMESPACE + '", e.g. ' + NAMESPACE + '.list()'
      );
    }
    let fn = target;
    for (const key of path.split('.')) fn = fn[key];
    return fn.apply(null, arguments);
  };

  return new Proxy(call, {
    get: function (_target, key) {
      if (typeof key === 'symbol') return undefined;
      return forward(path ? path + '.' + key : key);
    },
  });
}

const installed = globalThis[NAMESPACE];
const ns = installed === undefined || installed === null ? forward('') : installed;

export default ns;${namedExport}
`;
}

/**
 * esbuild plugin resolving bare specifiers that name an injected service
 * namespace to the generated virtual module above.
 *
 * Register it *before* `cdnTransformPlugin` in the plugin list.
 */
export function namespaceImportPlugin(
  options: NamespaceImportOptions = {},
): Plugin {
  const namespaces = extractNamespaces(options.services ?? []).filter((name) =>
    IDENTIFIER.test(name),
  );

  return {
    name: "patchwork-namespace-imports",
    setup(build) {
      if (namespaces.length === 0) return;

      const known = new Set(namespaces);
      // Exact roots only — `github/repos` and `./vfs` fall through untouched.
      const filter = new RegExp(`^(${namespaces.map(escapeRegExp).join("|")})$`);

      build.onResolve({ filter }, (args) => {
        if (!known.has(args.path)) return null;
        return { path: args.path, namespace: NAMESPACE_MODULE_NAMESPACE };
      });

      build.onLoad(
        { filter: /.*/, namespace: NAMESPACE_MODULE_NAMESPACE },
        (args) => ({
          contents: generateNamespaceModule(args.path),
          loader: "js" as const,
        }),
      );
    },
  };
}
